[project]
name = "wiki3ai"
version = "0.2.0"
description = "Wiki3.ai JupyterLite Site"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anywidget==0.9.21",
    "ipywidgets",
    "jupyterlab",
    "jupyterlite",
    "jupyterlite-core",
    "jupyterlite-pyodide-kernel",
    "jupyter-server",
    "matplotlib",
    "notebook",
    "numpy",
    "panel",
    "pandas",
    "tornado",
    "watchfiles",
    "wiki3-ai",
]

[project.optional-dependencies]
dev = [
    "pip",
    "jupyterlab",
]

[tool.uv.sources]
wiki3-ai = { path = "python-ai", editable = true }
